version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn package
      - mv webapp/target/webapp.war webapp.war
artifacts:
  files:
    - webapp.war
